### ISSUE TITLE
System Crashes When Feedback Button Pressed

### ISSUE THREAD

**Issue by BetaCoder124** [SweeZero/Elysium-Genesis-experience#1]

**Comment by Sweeistaken** [comment]
This isn't really a bug; I need to think about a feedback server. because my server could possibly get filled up because of my 512MB quota.

**Comment by BetaCoder124** [comment]
We should use a google forum, I will setup a system.

**Comment by Sweeistaken** [comment]
Okay, I will also make a google form and see who makes the best one.

**Comment by Sweeistaken** [comment]
but how do we automatically attach a dump of some kind?

**Comment by Sweeistaken** [comment]
The bug reporter will be implemented in qOS experience r2

**Comment by BetaCoder124** [comment]
Sounds good
